spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/herbie
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        glaobally_quoted-identifiers: true
        dialect: org.hibernate.dialect.MariaDBDialect

